### PR TITLE
Dev dials

### PR DESCRIPTION
**Pull request by dallanto**
Transfer of code, as much as possible, from the miniCBF input workflow to DIALS-expt.
Clone of the interface developed by Julian with necessary adaptation.
Inclusion of a 2-theta calculation function 
Note: This is incomplete from the functional point of view - the frames handling is not yet correctly implemented
The purpose of this review is to create a code reference (review optional).
@jamesrhester 
@kroon-lab

### CODE REVIEW

**Comment by takluyver** [comment]
@jamesrhester A quick question about part of your `get_two_theta` Julia function, which we're trying to copy in Python:

```julia
    if norm(normal - [0,0,1]) < 0.0001
        return 0.0, nothing
    end

    if normal[3] > 0 #pointing towards sample 
        normal = normal * -1.0
    end
```

As I understand this, the first `if` checks if the panel normal is parallel to the beam, in which case there's no rotation to calculate, and it bails out early. Then the second part makes sure we have a negative z dimension for the normal, since it could be pointing either in or out of the detector.

I think we want the parallel check to catch both `[0, 0, 1]` and `[0, 0, -1]` as equivalent, with no rotation needed. It looks like we can do that by swapping these two checks around and then changing `[0,0,1]` to `[0,0,-1]`. Does that make sense?

**Comment by jamesrhester** [comment]
Yes, those changes make sense and it looks like the Julia code has a bit of a bug.

**Comment by takluyver** [comment]
Thanks James! Are you the owner of this repo, and would you be happy to give me access so I can add commits to this PR?

**Comment by jamesrhester** [comment]
Done!

**Comment by takluyver** [comment]
Thanks! I've rebased the branch since Github thought there was a conflict, although I didn't actually have to fix any conflicts when I did so.

At this point, the Julia & Python code produce equivalent output for the example dataset Fabio pointed me to, differing only in whitespace, which I assume doesn't matter in the CIF format. The next step will be to try with some other datasets.

**Comment by dallanto** [comment]
Thanks, Thomas.  
ad [b7f74c1](https://github.com/COMCIFS/instrument-geometry-info/pull/70/commits/b7f74c1ac5567c8ce6562e293488a94066e0031c):
When porting from Julia to Python, I thought I should be compliant to the 0-indexing, but maybe in the context of this tool it is more intuitive to stay with 1-indexing as for Julia.

**Comment by takluyver** [comment]
I figured that the names like `ele1_x` vs. `ele0_x` probably didn't really matter, but I wasn't sure, so for now I just started by trying to match the output from the Julia version as closely as possible.

On this topic, did you mention that there's a tool for validating ImgCIF files? I found https://checkcif.iucr.org/index.html, which tells me 'No syntax errors found', but I don't get the impression it's checking anything beyond the syntax. And a way to check at the command line would be handy.

**Comment by jamesrhester** [comment]
Yes, element names and frame names don't matter, as long as they match. In general I find that users (as opposed to programmers) find counting objects from 1 more intuitive.

The online tool for validating imgCIF files is [here](https://publcif.iucr.org/imgcif/index.php)

You will probably prefer the command-line version, which is in [one of my repositories](https://github.com/jamesrhester/ImgCIFHandler.jl/tree/main/tools). The readme in that directory explains how to install and run. Raise an issue there if there is anything that is unclear or if it fails to install. I haven't put much effort into speeding it up to use recent Julia improvements (yet).

**Comment by jamesrhester** [comment]
Is there any reason we can't just merge all of this into `main`? It would make it easier to manage, I think.

**Pull request merged**
