### PR TITLE
Issue53 offset value

### PR DESCRIPTION
**Pull request by julianhoersch**
This PR addresses #53 
- The offset of the translation axis in the axis description is now set to zero.
- `goniometer_axes` in `hdf5_nxmx.py` is refactored to `axes` since it also contains detector axes.

### CODE REVIEW

**Comment by jamesrhester** [comment]
The value of the detector trans axis will now always be positive in the scan description, as the axis definition states that it increases when moving away from the source. So I don't think there is any need for the multiplication by `rot_sense[-1]`?

**Comment by julianhoersch** [comment]
ok. So I did remove the transformation of the translation axis in the scan description, now the values will be the same as found in the cbf header/hdf5:

`cbf_cyclohexane`
```
loop_
  _axis.id
  _axis.type
  _axis.equipment
  _axis.depends_on
  _axis.vector[1]
  _axis.vector[2]
  _axis.vector[3]
  _axis.offset[1]
  _axis.offset[2]
  _axis.offset[3]
         phi       rotation  goniometer          chi       1         0         0        0        0        0        
         chi       rotation  goniometer          omega     1         0         0        0        0        0        
         omega     rotation  goniometer          .         1         0         0        0        0        0        
         dety      translation         detector  detx      0         1         0        0        0        0        
         detx      translation         detector  distance  -1        0         0        16.77    -41.882  0        
         distance  translation         detector  detector_2theta     0         0        -1       0        0        0        
         detector_2theta     rotation  detector  .         1         0         0        0        0        0        
         gravity   .         gravity   .         -1        0         0         0        0        0        
         source    .         source    .         0         0         1         0        0        0
loop_
  _diffrn_scan_axis.scan_id
  _diffrn_scan_axis.axis_id
  _diffrn_scan_axis.displacement_start
  _diffrn_scan_axis.displacement_increment
  _diffrn_scan_axis.displacement_range
  _diffrn_scan_axis.angle_start
  _diffrn_scan_axis.angle_increment
  _diffrn_scan_axis.angle_range
         SCAN01    chi       .         .         .         -60.991   0         0        
         SCAN01    phi       .         .         .         -140.0    0         0        
         SCAN01    detector_2theta     .         .         .         12.4      0
          0         
         SCAN01    omega     .         .         .         -40.679   2.0       66.0     
         SCAN01    distance  40.0      0         
0         .         .         .        
```

and `_b4_master`


```
loop_
  _axis.id
  _axis.type
  _axis.equipment
  _axis.depends_on
  _axis.vector[1]
  _axis.vector[2]
  _axis.vector[3]
  _axis.offset[1]
  _axis.offset[2]
  _axis.offset[3]
         phi       rotation  goniometer          chi       1         -0.0037   0.002    0        0        0        
         chi       rotation  goniometer          omega     -0.0046   0.0372    -0.9993  0        0        0        
         omega     rotation  goniometer          .         1         0         0        0        0        0        
         two_theta           rotation  detector  .         1         0         0        0        0        0        
         dety      translation         detector  detx      0         -1        0        0        0        0        
         detx      translation         detector  trans     1         0         0        -166.87357         172.49715          0        
         trans     translation         detector  two_theta           0         0        -1       0        0        0
loop_
  _diffrn_scan_axis.scan_id
  _diffrn_scan_axis.axis_id
  _diffrn_scan_axis.displacement_start
  _diffrn_scan_axis.displacement_increment
  _diffrn_scan_axis.displacement_range
  _diffrn_scan_axis.angle_start
  _diffrn_scan_axis.angle_increment
  _diffrn_scan_axis.angle_range
         SCAN1     omega     .         .         .         0.0       0.1       360.0    
         SCAN1     trans     287.2224260231453   0         0         .         .        .
```

**Comment by kroon-lab** [comment]
@julianhoersch : did you generate the  cbf_cyclohexane from the mini cbf headers? The axes definition is entirely not correct. The version we used before is:
     _axis.id
      _axis.type
      _axis.equipment
      _axis.depends_on
      _axis.vector[1]
      _axis.vector[2]
      _axis.vector[3]
      _axis.offset[1]
      _axis.offset[2]
      _axis.offset[3]
         phi        rotation     goniometer  chi        1   0  0   0  0  0
         chi        rotation     goniometer  omega      0   0  -1   0  0  0
         omega      rotation     goniometer  .          1   0  0   0  0  0
         two_theta  rotation     detector    .          1   0  0   0  0  0
         trans      translation  detector    two_theta  0   0  -1  0  0  0
         detx       translation  detector    trans      0  -1  0   41.882 16.7 0
         dety       translation  detector    detx       -1  0  0   0  0  0

So `phi `and `omega` are correct. `Chi `should be [ 0 0 -1]. The `distance `data name seems to lack a `0 `at the end.
`detx `should be [ 0 -1 0] and `dety` [ -1 0 0] . Therefore also the offset should be [41.882 16.7 0] instead of [16.7 -41.882 0].
All dependencies are correct.

**Comment by kroon-lab** [comment]
OK, so the distance now goes into   `_diffrn_scan_axis.displacement_start.` That is fine with me, but is "breaks" with our earlier approach.

**Comment by julianhoersch** [comment]
ah, sorry, I've just used a random input in the creator to produce that file out of the cbf files.... it should not represent the actual axis description.
I think you can scroll that code window horizontally - than there should be the missing `0`.
You can decide what's the best approach where to put the `displacement_start`, but for multiple values it might be better to put it into the scan description.

**Comment by kroon-lab** [comment]
OK, yes, I can scroll. Thanks. To have the distance in _diffrn_scan_axis.displacement_start is a good approach. All other axes values are also in _diffrn_scan_axis.

**Comment by kroon-lab** [comment]
@julianhoersch : can you resolve the conflicts?

**Comment by julianhoersch** [comment]
I think if I put in the right information the description is correct:

```
loop_
  _axis.id
  _axis.type
  _axis.equipment
  _axis.depends_on
  _axis.vector[1]
  _axis.vector[2]
  _axis.vector[3]
  _axis.offset[1]
  _axis.offset[2]
  _axis.offset[3]
         phi       rotation  goniometer          chi       1         0         0        0        0        0        
         chi       rotation  goniometer          omega     0         0         -1       0        0        0        
         omega     rotation  goniometer          .         1         0         0        0        0        0        
         dety      translation         detector  detx      -1        0         0        0        0        0        
         detx      translation         detector  distance  0         -1        0        41.882   16.77    0        
         distance  translation         detector  detector_2theta     0         0        -1       0        0        -40      
         detector_2theta     rotation  detector  .         1        0         0        0        0        0        
         gravity   .         gravity   .         -1        0         0         0        0        0        
         source    .         source    .         0         0         1         0        0        0
```

note that I have used `phi, a, chi, a, omega, a`, since there was some mistake in #20

**Pull request merged**
